# Configure the basic properties of the prompt
add_newline = false
"$schema" = 'https://starship.rs/config-schema.json'

# Format the symbols
[character] 
success_symbol = '[➜](bold green)' 
error_symbol = '[✗](bold red)'

# Format the directories path
[directory]
truncation_length = 3
truncate_to_repo = false
truncation_symbol = '.../'

# Format conda information
[conda]
format = '[$symbol$environment](dimmed green) '

# Format git information
[git_branch]
symbol = "  "
style = "bold purple"
truncation_length = 10
truncation_symbol = '.../'
ignore_branches = []
format = "[$symbol$branch(:$remote_branch) ]($style)"

# Format the memory usage
[memory_usage]
disabled = true
threshold = -1
symbol = '🐏'
style = 'bold dimmed green'
format = "$symbol [${ram}]($style) "

# Format the command durantion
[cmd_duration]
min_time = 1_000
show_milliseconds = true
format = "took [$duration]($style)"
