# Inserts a blank line between shell prompts
add_newline = false

# Format the symbols
[character] 
success_symbol = '[➜](bold green)' 
error_symbol = '[✗](bold red)'

# Format the directories path
[directory]
truncation_length = 3
truncate_to_repo = false
truncation_symbol = '.../'

# Format conda information
[conda]
format = '[$symbol$environment](dimmed green) '

# Format git information
[git_branch]
symbol = "🌱 "
style = "bold purple"
truncation_length = 10
truncation_symbol = '.../'
ignore_branches = []

